# Data
data_name: 'yelp'
data_dir: './data/'
train_ratio: 0.4
test_ratio: 0.67
save_dir: "/data/PC-GNN_models/"

# Model
model: 'PCGNN'
multi_relation: 'GNN'


# Model architecture
emb_size: 64

thres: 0.5

rho: 0.5
# rho:
#   - 0.2
#   - 0.4
#   - 0.6
#   - 0.8

seed: 72

# # Run multiple times with different random seeds
# seed:
#     - 42
#     - 448
#     - 854
#     - 29493
#     - 88867


# hyper-parameters
optimizer: 'adam'
lr: 0.01 
weight_decay: 0.001
batch_size: 1024
num_epochs: 101
valid_epochs: 5
alpha: 2


# Device
no_cuda: False
cuda_id: '2'
